num1 = float(input("Enter the first Num: "))
num2 = float(input("Enter the second Num: "))
num3 = float(input("Enter the third Num: "))
max_num = max(num1, num2, num3)
print("The maximum of the three numbers is", max_num)
